[project]
name = "fast-t2t"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pierrot LC", email = "pierrotlc@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "cython>=3.3.0",
    "numpy>=2.5.3",
    "pytorch-lightning==2.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch==2.11.0",
    "torch-geometric>=2.8.0.post1",
    "wandb>=0.30.0",
]

[tool.uv.extra-build-dependencies]
torch-sparse = ["torch"]
torch-scatter = ["torch"]

[[tool.uv.index]]
url = "https://data.pyg.org/whl/torch-2.11.0+cu130.html"

[project.scripts]
fast-t2t = "fast_t2t:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
